import { StyleSheet } from "react-native"
export const tw = StyleSheet.create({
    /** Layout */
    flex: { flex: 1 },
    flexNone: { flex: 0 },
    flexRow: { flexDirection: 'row' },
    flexCol: { flexDirection: 'column' },
    flexWrap: { flexWrap: 'wrap' },
    flexNowrap: { flexWrap: 'nowrap' },
    justifyStart: { justifyContent: 'flex-start' },
    justifyCenter: { justifyContent: 'center' },
    justifyEnd: { justifyContent: 'flex-end' },
    justifyBetween: { justifyContent: 'space-between' },
    justifyAround: { justifyContent: 'space-around' },
    justifyEvenly: { justifyContent: 'space-evenly' },
    itemsStart: { alignItems: 'flex-start' },
    itemsCenter: { alignItems: 'center' },
    itemsEnd: { alignItems: 'flex-end' },
    selfStart: { alignSelf: 'flex-start' },
    selfCenter: { alignSelf: 'center' },
    selfEnd: { alignSelf: 'flex-end' },
  
    /** Spacing */
    m0: { margin: 0 },
    m5: { margin: 5 },
    m10: { margin: 10 },
    m20: { margin: 20 },
    p0: { padding: 0 },
    p5: { padding: 5 },
    p10: { padding: 10 },
    p20: { padding: 20 },
    mt5: { marginTop: 5 },
    mt10: { marginTop: 10 },
    mb5: { marginBottom: 5 },
    mb10: { marginBottom: 10 },
    ml5: { marginLeft: 5 },
    ml10: { marginLeft: 10 },
    mr5: { marginRight: 5 },
    mr10: { marginRight: 10 },
    pt5: { paddingTop: 5 },
    pt10: { paddingTop: 10 },
    pb5: { paddingBottom: 5 },
    pb10: { paddingBottom: 10 },
    pl5: { paddingLeft: 5 },
    pl10: { paddingLeft: 10 },
    pr5: { paddingRight: 5 },
    pr10: { paddingRight: 10 },
  
    /** Size */
    wFull: { width: '100%' },
    hFull: { height: '100%' },
    w50: { width: '50%' },
    h50: { height: '50%' },
    w100: { width: 100 },
    h100: { height: 100 },
  
    /** Borders */
    rounded: { borderRadius: 8 },
    roundedSm: { borderRadius: 4 },
    roundedLg: { borderRadius: 16 },
    roundedFull: { borderRadius: 9999 },
    border: { borderWidth: 1, borderColor: '#e5e7eb' }, // light gray border
    border2: { borderWidth: 2 },
    borderGray300: { borderColor: '#D1D5DB' },
    borderBlue500: { borderColor: '#3B82F6' },
  
    /** Background Colors */
    bgWhite: { backgroundColor: '#ffffff' },
    bgGray100: { backgroundColor: '#f3f4f6' },
    bgGray300: { backgroundColor: '#d1d5db' },
    bgBlue500: { backgroundColor: '#3B82F6' },
    bgRed500: { backgroundColor: '#EF4444' },
    bgGreen500: { backgroundColor: '#22C55E' },
  
    /** Text */
    textWhite: { color: '#ffffff' },
    textBlack: { color: '#000000' },
    textGray700: { color: '#374151' },
    textBlue500: { color: '#3B82F6' },
    textRed500: { color: '#EF4444' },
    textCenter: { textAlign: 'center' },
    textLeft: { textAlign: 'left' },
    textRight: { textAlign: 'right' },
    textXs: { fontSize: 12 },
    textSm: { fontSize: 14 },
    textBase: { fontSize: 16 },
    textLg: { fontSize: 18 },
    textXl: { fontSize: 20 },
    fontBold: { fontWeight: 'bold' },
    fontMedium: { fontWeight: '500' },
    fontLight: { fontWeight: '300' },
  
    /** Shadows */
    shadowSm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.18,
      shadowRadius: 1.0,
      elevation: 1,
    },
    shadowMd: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 2,
    },
    shadowLg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
  });